/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MtConnect {
        "connect": number;
    }
}
declare global {
    interface HTMLMtConnectElement extends Components.MtConnect, HTMLStencilElement {
    }
    var HTMLMtConnectElement: {
        prototype: HTMLMtConnectElement;
        new (): HTMLMtConnectElement;
    };
    interface HTMLElementTagNameMap {
        "mt-connect": HTMLMtConnectElement;
    }
}
declare namespace LocalJSX {
    interface MtConnect {
        "connect"?: number;
    }
    interface IntrinsicElements {
        "mt-connect": MtConnect;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mt-connect": LocalJSX.MtConnect & JSXBase.HTMLAttributes<HTMLMtConnectElement>;
        }
    }
}
